# Generated by Django 4.2.2 on 2023-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reservabanho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de Contato', 'verbose_name_plural': 'Formulários de Contatos'},
        ),
        migrations.AddField(
            model_name='contato',
            name='lido',
            field=models.BooleanField(blank=True, default=False, verbose_name='Lido'),
        ),
        migrations.AlterField(
            model_name='reservabanho',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
